---
services:
  calibre-web-automated:
    image: ghcr.io/peuin/ocdlibary:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - HARDCOVER_TOKEN=${HARDCOVER_TOKEN:-}
      - NETWORK_SHARE_MODE=false
    volumes:
      - ./config:/config
      - ./ingest:/cwa-book-ingest
      - ./library:/calibre-library
      # - ./plugins:/config/.config/calibre/plugins
    ports:
      - 8083:8083
    restart: unless-stopped
